/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-04-09 13:21:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647478579039L));
    _jspx_dependants.put("jar:file:/C:/Users/nguyen%20viet%20hien/OneDrive/Máy%20tính/Java4/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/HiennvPH13697_SOF3011_Assignment/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"icon\"\r\n");
      out.write("	href=\"/HiennvPH13697_SOF3011_Assignment/images/logo.png\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/HiennvPH13697_SOF3011_Assignment/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"/HiennvPH13697_SOF3011_Assignment/codeCss/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<header class=\"my-3 text-center\">\r\n");
      out.write("			<a href=\"/HiennvPH13697_SOF3011_Assignment/home\"><img\r\n");
      out.write("				src=\"/HiennvPH13697_SOF3011_Assignment/images/logo.png\"\r\n");
      out.write("				style=\"width: 64px; height: 64px\" class=\"my-3\" alt=\"\" /></a>\r\n");
      out.write("			<p class=\"fw-bold\">Bài Assignment của Nguyễn Viết Hiên</p>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("		<nav\r\n");
      out.write("			class=\"navbar navbar-expand-lg navbar-light bg-light sticky-top fw-bold\">\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<ul class=\"navbar-nav\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\r\n");
      out.write("						href=\"/HiennvPH13697_SOF3011_Assignment/home\">Trang chủ</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("					data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavDropdown\"\r\n");
      out.write("					aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"collapse navbar-collapse row px-3\"\r\n");
      out.write("					id=\"navbarNavDropdown\">\r\n");
      out.write("					<ul class=\"navbar-nav col-12 col-md-12 col-lg-10\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Giới\r\n");
      out.write("								thiệu</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("							href=\"/HiennvPH13697_SOF3011_Assignment/list-products\">Sản\r\n");
      out.write("								phẩm</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Liên hệ</a></li>\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Hỏi đáp</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul\r\n");
      out.write("						class=\"navbar-nav col-12 col-md-12 col-lg-2 justify-content-end p-0\">\r\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"/HiennvPH13697_SOF3011_Assignment/cart\"> <i\r\n");
      out.write("								class=\"bi bi-bag\"></i>\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"nav-item dropdown\"><a\r\n");
      out.write("							class=\"nav-link dropdown-toggle\" href=\"#\"\r\n");
      out.write("							id=\"navbarDropdownMenuLink\" role=\"button\"\r\n");
      out.write("							data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> <i\r\n");
      out.write("								class=\"bi bi-person-circle\"></i> ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</a>\r\n");
      out.write("							<ul class=\"dropdown-menu\"\r\n");
      out.write("								aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<!-- 		<div class=\"modal fade\" id=\"dangNhap\" tabindex=\"-1\" -->\r\n");
      out.write("		<!-- 			aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\"> -->\r\n");
      out.write("		<!-- 			<div class=\"modal-dialog\"> -->\r\n");
      out.write("		<!-- 				<div class=\"modal-content\"> -->\r\n");
      out.write("		<!-- 					<div class=\"modal-header\"> -->\r\n");
      out.write("		<!-- 						<h5 class=\"modal-title\" id=\"exampleModalLabel\">LOGIN</h5> -->\r\n");
      out.write("		<!-- 						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" -->\r\n");
      out.write("		<!-- 							aria-label=\"Close\"></button> -->\r\n");
      out.write("		<!-- 					</div> -->\r\n");
      out.write("		<!-- 					<div class=\"modal-body\"> -->\r\n");
      out.write("		<!-- 						<from action=\"\" method=\"\"> <lable class=\"form-lable\">Tài -->\r\n");
      out.write("		<!-- 						khoản</lable> <input class=\"form-control\" type=\"email\" name=\"\"> <lable -->\r\n");
      out.write("		<!-- 							class=\"form-lable\">Mật khẩu</lable> <input class=\"form-control\" -->\r\n");
      out.write("		<!-- 							type=\"password\" name=\"\"> -->\r\n");
      out.write("		<!-- 						<div class=\"row mb-3\"> -->\r\n");
      out.write("		<!-- 							<div class=\"col-6\"> -->\r\n");
      out.write("		<!-- 								<div class=\"form-check mt-3\"> -->\r\n");
      out.write("		<!-- 									<input class=\"form-check-input\" type=\"checkbox\" value=\"\" -->\r\n");
      out.write("		<!-- 										id=\"flexCheckDefault\" /> <label class=\"form-check-labe\" -->\r\n");
      out.write("		<!-- 										for=\"flexCheckDefault\"> Remember Me! </label> -->\r\n");
      out.write("		<!-- 								</div> -->\r\n");
      out.write("		<!-- 							</div> -->\r\n");
      out.write("		<!-- 							<div class=\"col-6\"> -->\r\n");
      out.write("		<!-- 								<a class=\"float-end mt-3\" href=\"#\" data-bs-toggle=\"modal\" -->\r\n");
      out.write("		<!-- 									data-bs-target=\"#ForgotPassword\">Forgot Password?</a> -->\r\n");
      out.write("		<!-- 							</div> -->\r\n");
      out.write("		<!-- 						</div> -->\r\n");
      out.write("		<!-- 						<div class=\"text-center\"> -->\r\n");
      out.write("		<!-- 							<a href=\"#\" class=\"btn btn-secondary mb-3\"> Login Now</a> -->\r\n");
      out.write("		<!-- 						</div> -->\r\n");
      out.write("		<!-- 						<div class=\"text-center\"> -->\r\n");
      out.write("		<!-- 							<span>Need an account?</span> <a href=\"/HiennvPH13697_SOF3011_Assignment/users/create\"> Sign Up </a> -->\r\n");
      out.write("		<!-- 						</div> -->\r\n");
      out.write("		<!-- 						<hr /> -->\r\n");
      out.write("		<!-- 						<div class=\"text-center\"> -->\r\n");
      out.write("		<!-- 							<button type=\"button\" class=\"btn btn-outline-secondary\"> -->\r\n");
      out.write("		<!-- 								<i class=\"bi bi-facebook\"></i> Login with Facebook -->\r\n");
      out.write("		<!-- 							</button> -->\r\n");
      out.write("		<!-- 						</div> -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 						</from> -->\r\n");
      out.write("		<!-- 					</div> -->\r\n");
      out.write("		<!-- 				</div> -->\r\n");
      out.write("		<!-- 			</div> -->\r\n");
      out.write("		<!-- 		</div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ view }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<button type=\"button\"\r\n");
      out.write("			class=\"btn btn-outline-secondary btn-floating btn-lg text-center\"\r\n");
      out.write("			id=\"btn-back-to-top\">\r\n");
      out.write("			<i class=\"bi bi-arrow-up\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("		<footer class=\"text-center bg-secondary text-white p-3 mt-3\">\r\n");
      out.write("			<p class=\"m-0\">@2021 - design by Nguyễn Viết Hiên</p>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"/HiennvPH13697_SOF3011_Assignment/codeJs/linkJs.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"/HiennvPH13697_SOF3011_Assignment/js/sweetalert2.all.min.js\"></script>\r\n");
      out.write("	<script src=\"/HiennvPH13697_SOF3011_Assignment/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/HiennvPH13697_SOF3011_Assignment/js/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"/HiennvPH13697_SOF3011_Assignment/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/layout.jsp(60,41) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty userLogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userLogin.hoTen }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /views/layout.jsp(63,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty userLogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									Tài khoản\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /views/layout.jsp(70,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty userLogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<li><a\r\n");
          out.write("										href=\"/HiennvPH13697_SOF3011_Assignment/accounts/login\"\r\n");
          out.write("										class=\"dropdown-item\">Đăng nhập</a></li>\r\n");
          out.write("									<li><a\r\n");
          out.write("										href=\"/HiennvPH13697_SOF3011_Assignment/accounts/register\"\r\n");
          out.write("										class=\"dropdown-item\">Đăng ký</a></li>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /views/layout.jsp(78,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty userLogin}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									<li><a href=\"#\" class=\"dropdown-item\"\r\n");
          out.write("										data-bs-toggle=\"modal\" data-bs-target=\"#doiMatKhau\">Đổi\r\n");
          out.write("											mật khẩu</a></li>\r\n");
          out.write("									<li><a class=\"dropdown-item\" href=\"#\">Cập nhật tài\r\n");
          out.write("											khoản</a></li>\r\n");
          out.write("									<li><a class=\"dropdown-item\"\r\n");
          out.write("										href=\"/HiennvPH13697_SOF3011_Assignment/accounts/logout\">Đăng\r\n");
          out.write("											xuất</a></li>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /views/layout.jsp(79,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userLogin.phanQuyen == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<li><a\r\n");
          out.write("											href=\"/HiennvPH13697_SOF3011_Assignment/users/index\"\r\n");
          out.write("											class=\"dropdown-item\">Quản lý người dùng</a></li>\r\n");
          out.write("										<li><a\r\n");
          out.write("											href=\"/HiennvPH13697_SOF3011_Assignment/products/index\"\r\n");
          out.write("											class=\"dropdown-item\">Quản lý sản phẩm</a></li>\r\n");
          out.write("										<li><a\r\n");
          out.write("											href=\"/HiennvPH13697_SOF3011_Assignment/categories/index\"\r\n");
          out.write("											class=\"dropdown-item\">Quản lý loại sản phẩm</a></li>\r\n");
          out.write("										<li><a\r\n");
          out.write("											href=\"/HiennvPH13697_SOF3011_Assignment/carts/index\"\r\n");
          out.write("											class=\"dropdown-item\">Quản lý đơn hàng</a></li>\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
