/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-04-09 01:00:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1647478579039L));
    _jspx_dependants.put("jar:file:/C:/Users/nguyen%20viet%20hien/OneDrive/Máy%20tính/Java4/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/HiennvPH13697_SOF3011_Assignment/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"trangChu\">\r\n");
      out.write("	<div class=\"row mt-3\">\r\n");
      out.write("		<article class=\"col-12 slide-show-img\">\r\n");
      out.write("			<div id=\"carouselExampleControls\" class=\"carousel slide\"\r\n");
      out.write("				data-bs-ride=\"carousel\" data-bs-interval=\"2000\">\r\n");
      out.write("				<div class=\"carousel-inner\">\r\n");
      out.write("					<div class=\"carousel-item active\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://file.vfo.vn/hinh/2015/12/meo-con-dang-yeu-lam-hinh-nen-may-tinh-4.jpg\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"carousel-item\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://file.vfo.vn/hinh/2015/12/meo-con-dang-yeu-lam-hinh-nen-may-tinh-5.jpg\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"carousel-item\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://file.vfo.vn/hinh/2015/12/meo-con-dang-yeu-lam-hinh-nen-may-tinh-6.jpg\"\r\n");
      out.write("							alt=\"...\" />\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("					data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"prev\">\r\n");
      out.write("					<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("					<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("				</button>\r\n");
      out.write("				<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("					data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"next\">\r\n");
      out.write("					<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("					<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</article>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("	<div class=\"row mt-3\">\r\n");
      out.write("		<div class=\"text-center col-12 mb-3\">\r\n");
      out.write("			<h1 class=\"border border-2 border-secondary px-2 d-inline fw-bold\">\r\n");
      out.write("				Sản phẩm</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("	<div class=\"row product_border\">\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"text-center my-3\">\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("			<a href=\"#\" class=\"text-black text-decoration-none\">Xem Tất Cả</a>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("	<div class=\"row mt-3\">\r\n");
      out.write("		<div class=\"title-text text-center mb-3\">\r\n");
      out.write("			<h1 class=\"border border-2 border-secondary px-2 d-inline fw-bold\">\r\n");
      out.write("				Môn học phổ biến.</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/java.jpg\" alt=\"\" class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/html.jpg\" alt=\"\" class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/javascript.jpg\" alt=\"\"\r\n");
      out.write("				class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/angularjs.jpg\" alt=\"\"\r\n");
      out.write("				class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-12 anh-tuong-trung\">\r\n");
      out.write("			<img src=\"Images/javascript.jpg\" alt=\"\" class=\"img-fluid w-100 my-5\" />\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("	<div class=\"row mt-3\">\r\n");
      out.write("		<div class=\"title-text text-center mb-3\">\r\n");
      out.write("			<h1 class=\"border border-2 border-secondary px-2 d-inline fw-bold\">\r\n");
      out.write("				Môn học khác.</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/java.jpg\" alt=\"\" class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/html.jpg\" alt=\"\" class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/javascript.jpg\" alt=\"\"\r\n");
      out.write("				class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-3 col-12\">\r\n");
      out.write("			<a href=\"#\"> <img src=\"Images/angularjs.jpg\" alt=\"\"\r\n");
      out.write("				class=\"img-fluid\" />\r\n");
      out.write("			</a>\r\n");
      out.write("			<p class=\"text-center\">\r\n");
      out.write("				<a class=\"text-black noi-bat\" href=\"#\">Lorem ipsum dolor sit,\r\n");
      out.write("					amet consectetur adipisicing elit.</a>\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr />\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/admin/home.jsp(48,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("prd");
      // /views/admin/home.jsp(48,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ dsPrd }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("			<div class=\"col-12 col-md-3\">\r\n");
            out.write("				<div class=\"container_overlay title-img\">\r\n");
            out.write("					<a href=\"/HiennvPH13697_SOF3011_Assignment/product?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ prd.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"> \r\n");
            out.write("					<img\r\n");
            out.write("						src=\"/HiennvPH13697_SOF3011_Assignment/images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ prd.img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("						alt=\"Avatar\" class=\"image_product img-fluid\" />\r\n");
            out.write("					</a>\r\n");
            out.write("<!-- 					<div class=\"overlay\"> -->\r\n");
            out.write("<!-- 						<div class=\"img_hover\"> -->\r\n");
            out.write("<!-- 							<a href=\"#\"> <img -->\r\n");
            out.write("<!-- 								src=\"https://media.coolmate.me/uploads/January2022/nnjkids123_s1_672x990.jpg\" -->\r\n");
            out.write("<!-- 								alt=\"Avatar\" class=\"image_product\" /> -->\r\n");
            out.write("<!-- 							</a> -->\r\n");
            out.write("<!-- 						</div> -->\r\n");
            out.write("<!-- 					</div> -->\r\n");
            out.write("				</div>\r\n");
            out.write("				<div class=\"text-center\">\r\n");
            out.write("					<a class=\"product_name\" href=\"#\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ prd.category.ten }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ khoangTrang }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ prd.ten }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("					<p class=\"product_price\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ prd.donGia }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
